[package]
name = "image-tagger"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <you@example.com>"]
description = "An image tagging application using egui and image."
license = "MIT"

[dependencies]
# UI framework
eframe = "0.25"         # or the latest stable version
egui = "0.25"           # ensure matching version with eframe

# Image decoding and processing
image = "0.24"           # or latest stable version

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Directory traversal
walkdir = "2.3"

# File dialogs
rfd = "0.6"              # or latest stable version

# Thread-safe collections
parking_lot = "0.12"      # If you prefer parking_lot for synchronization (optional)

# Parallel processing (optional, only if you kept the rayon lines in your code)
rayon = "1.7"

[profile.release]
# Optional: for faster builds or specific optimizations
